<?php

use \Drupal\node\Entity\Node;

function boatmanagement_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'node_bateau_edit_form'){
    $form['fichier_csv_import'] = [
      '#type' => 'managed_file',
      '#title' => 'Fichier CSV Import',
      '#weight' => '0'
    ];

    $form['actions']['submit']['#submit'][] = 'bateau_edit_send_email';
  }
}

function bateau_edit_send_email(&$form, &$form_state){
  //On charge le service d'envoi de mail
  $mailer = \Drupal::service('plugin.manager.mail');
  // On récupère la langue de l'utilisateur cournat
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  // On récupère le nom du site dans la config pour le mettre dans le sujet du mail
  $site_name = \Drupal::config('system.site')->get('name');
  //On récupère l'utilisateur actuellement connecté
  $current_user = \Drupal::currentUser();
  $expediteur = $current_user->getEmail();
  //On construit le tableau avec les paramètres pour l'envoi du mail
  $subject = t('Modification de votre fiche bateau');
  $content = t('Votre fiche de bateau a été modifiée');
  $params = array(
    'message' => $content,
    'subject' => $site_name.$subject,
  );

  //On récupère le noeud por trouver le propriétaire du bateau qui a été modifié
  $node = Node::load($form_state->getValue('nid'));

  //Le champ propriétaire contient une référence vers une entité User, il faut donc la chargé pour récupérer le mail du propriétaire
  /** @var \Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem $referenceItem */
  $referenceItem = $node->get('field_proprietaire')->first();

  /** @var \Drupal\Core\Entity\Plugin\DataType\EntityReference $entityReference */
  $entityReference = $referenceItem->get('entity');

  /** @var \Drupal\Core\Entity\Plugin\DataType\EntityAdapter $entityAdapter */
  $entityAdapter = $entityReference->getTarget();

  /** @var \Drupal\Core\Entity\EntityInterface $referencedEntity */
  $proprietaire = $entityAdapter->getValue();

  $destinataire = $proprietaire->getEmail();

  //On envoie le mail avec toutes les infos dont on a besoin

  $mailer->mail('boatmanagement', 'bateau_edit_send_email', $destinataire, $langcode, $params, $expediteur, $send=TRUE );
}